# Generated by Django 4.0.1 on 2022-01-29 15:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='URL')),
                ('text', models.TextField(blank=True, verbose_name='Full Text')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Image')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=True, verbose_name='Is published')),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Comments', to='main.post')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
