# Generated by Django 4.0.1 on 2022-02-01 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_category_productcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField(max_length=1500)),
                ('rating', models.SmallIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Review', to='main.product')),
            ],
            options={
                'ordering': ('product',),
            },
        ),
        migrations.DeleteModel(
            name='ProductComment',
        ),
    ]
