# Generated by Django 4.0.1 on 2022-02-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_product_total_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
    ]
